### ISSUE TITLE
Make prediction errors

### ISSUE THREAD

**Issue by hsarimv** [KinkyDesign/JaqpotQuattroUI#62]
Both production and test versions give errors when trying to make predictions

**Comment by hampos** [comment]
This is an issue that is caused by database migration from test to production, the namespace is different so the model does not find it's required features in the dataset.
I re-created the example models in the production server and now they work, but all other custom user models migrated from test will not work.

**Comment by hsarimv** [comment]
Still getting error messages in both production and test
