### ISSUE TITLE
report pdf issues

### ISSUE THREAD

**Issue by gdrakakis** [KinkyDesign/JaqpotQuattroUI#95]
1. general info not in report. example: title, dataset and model not present in validation report
2. names in tables are saved as <a href ... This should be names (and if possible links)

**Comment by AValsamis** [comment]
@gdrakakis 1. is solved. Regarding 2., I cant find any names saved as <a href ..  Can you pinpoint me to the specific report name (found in url, e.g. http://test.jaqpot.org/report?name= **l5g3ipwCtm5UBS2**)?

**Comment by gdrakakis** [comment]
for some reason I cannot run anything at the moment. but here is a screenshot of an external  validation report I saved as pdf
![image](https://cloud.githubusercontent.com/assets/10755430/18274775/d184d2d8-744c-11e6-8810-8df98c22dacd.png)

**Comment by AValsamis** [comment]
@gdrakakis  @hampos  Second part of this issue is resolved by https://github.com/KinkyDesign/JaqpotQuattro/commit/1f95a44e93a7ee7f177a4a0346fa90da5b2ba2d5. After building the last commit, links should look like this:

![tosend](https://cloud.githubusercontent.com/assets/11833882/18443349/387a5f60-791d-11e6-91b4-55c766ad46e9.png)
